### ISSUE TITLE
Allow the handler to handler multiple user signals

### ISSUE THREAD

**Issue by dwhitters** [dwhitters/Signal_Handler#1]
**Problem**
The program does not continuously get interrupted by the child process.
It gets interrupted once then must be exited using the CTRL+C command.

**Proposed Solution**
1. The problem may be that the child process is exiting prematurely. Have it exit only on SIGINT.

**Comment by jbukowsky97** [comment]
commit: 05c95012ce1e7a8f298259423d2ada30e54242d5

Fixed.
